# -*- coding: utf-8 -*-
"""Bitcoin_Daily_Return

Automatically generated by Colaboratory.
"""

#Description: This program gets BTC's daily simple return

# Install dependencies
! pip install -U pandas_datareader

# Import the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
import pandas_datareader as web
plt.style.use('fivethirtyeight')

#Load the data

start = dt.datetime(2016, 1, 1)
end = dt.datetime.now()

df = web.DataReader(
    'BTC-USD',
    'yahoo',
    start,
    end
)

df

#Visually show and plot the close price
plt.figure(figsize=(14,7))
plt.title('Close Price', fontsize=18)
plt.plot(df['Close'])
plt.xlabel('Date', fontsize=18)
plt.ylabel('Close Price', fontsize=18)
plt.show()

# Calculate and show the Daily Simple Return
DSR = df['Close'].pct_change()
DSR

# Get some statistics on the DSR
DSR.describe()

# Visually show and plot the DSR
plt.figure(figsize=(14,7))
plt.title('Daily Simple Returns', fontsize=18)
plt.plot(DSR.index, DSR, label='DSR', lw=2, alpha=0.7)
plt.xlabel('Date', fontsize=18)
plt.ylabel('Percentage', fontsize=18)
plt.xticks(rotation=45)
plt.show()

# Put the teo chars together
#First plot the close price
top = plt.subplot2grid((4,4), (0,0), rowspan=3, colspan=4)
top.plot(df.index, df['Close'], label='Close')
plt.title('Close Price')
plt.legend(loc='upper left')
# Plot the DSR
bottom = plt.subplot2grid((4,4), (3,0), rowspan=1, colspan=4)
plt.title('DSR')
bottom.plot(DSR.index, DSR)
plt.subplots_adjust(hspace=0.75)
plt.gcf().set_size_inches(15,8)
